name: call_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  zego_uikit: ^2.27.17
  zego_uikit_prebuilt_call: ^4.16.15
  zego_uikit_signaling_plugin: ^2.8.8

  faker: ^2.2.0
  shared_preferences: ^2.3.3
  flutter_styled_toast: ^2.2.1

  # firebase_core: ^3.8.1
  # firebase_auth: ^5.3.4
  # cloud_firestore: ^5.5.1
  # flutter_contacts: ^1.1.9+2

  firebase_core:
  firebase_auth:
  cloud_firestore:
  flutter_contacts: ^1.1.9+2

  # flutter_riverpod: ^2.6.1
  # go_router: ^14.6.2
  # flutter_pitel_voip: ^1.0.8+4
  # package_info_plus: ^3.1.2
  # flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
