// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSQ9gDzmiKwJTTc-8ahl-Uu6gUWcpPxic',
    appId: '1:724074377990:web:2c8aac0fcaa73e845fa487',
    messagingSenderId: '724074377990',
    projectId: 'callapp-9e510',
    authDomain: 'callapp-9e510.firebaseapp.com',
    storageBucket: 'callapp-9e510.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDDAlGlUwDbW7NqudJu15K3nIswbWAIK4',
    appId: '1:724074377990:android:fe1d2895e4d19d4c5fa487',
    messagingSenderId: '724074377990',
    projectId: 'callapp-9e510',
    storageBucket: 'callapp-9e510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjalrajq3cl9Kd1VxGuwPqgP9459zo-sM',
    appId: '1:724074377990:ios:3e75e33bfd0e5df45fa487',
    messagingSenderId: '724074377990',
    projectId: 'callapp-9e510',
    storageBucket: 'callapp-9e510.firebasestorage.app',
    iosBundleId: 'com.example.callApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjalrajq3cl9Kd1VxGuwPqgP9459zo-sM',
    appId: '1:724074377990:ios:3e75e33bfd0e5df45fa487',
    messagingSenderId: '724074377990',
    projectId: 'callapp-9e510',
    storageBucket: 'callapp-9e510.firebasestorage.app',
    iosBundleId: 'com.example.callApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSQ9gDzmiKwJTTc-8ahl-Uu6gUWcpPxic',
    appId: '1:724074377990:web:a0b2b73f8be427505fa487',
    messagingSenderId: '724074377990',
    projectId: 'callapp-9e510',
    authDomain: 'callapp-9e510.firebaseapp.com',
    storageBucket: 'callapp-9e510.firebasestorage.app',
  );
}
